/* 英語：初級・中級・上級 各30問 */
const ENGLISH_L1 = [
  { q: "「私は学生です」を選べ", choices: ["I am a student.", "I is a student.", "I are a student.", "I be a student."], a: 0 },
  { q: "「あなたは先生です」を選べ", choices: ["You am a teacher.", "You is a teacher.", "You are a teacher.", "You be a teacher."], a: 2 },
  { q: "「これは本です」を選べ", choices: ["This is a book.", "This am a book.", "This are a book.", "This be a book."], a: 0 },
  { q: "「あれは犬です」を選べ", choices: ["That is a dog.", "That am a dog.", "That are a dog.", "That be a dog."], a: 0 },
  { q: "「犬」の複数形は？", choices: ["dogs", "doges", "dogies", "dogs's"], a: 0 },
  { q: "「猫」の複数形は？", choices: ["cats", "cates", "caties", "cat's"], a: 0 },
  { q: "「箱」の複数形は？", choices: ["boxs", "boxes", "boxies", "box's"], a: 1 },
  { q: "\"I ___ a student.\" に入る語は？", choices: ["am", "is", "are", "be"], a: 0 },
  { q: "\"She ___ a nurse.\" に入る語は？", choices: ["am", "is", "are", "be"], a: 1 },
  { q: "\"They ___ friends.\" に入る語は？", choices: ["am", "is", "are", "be"], a: 2 },
  { q: "「大きい」を表す語は？", choices: ["small", "big", "long", "short"], a: 1 },
  { q: "「小さい」を表す語は？", choices: ["big", "small", "tall", "wide"], a: 1 },
  { q: "「新しい」を表す語は？", choices: ["old", "new", "young", "used"], a: 1 },
  { q: "\"apple\" の意味は？", choices: ["みかん", "りんご", "ぶどう", "もも"], a: 1 },
  { q: "\"dog\" の意味は？", choices: ["猫", "鳥", "犬", "魚"], a: 2 },
  { q: "\"school\" の意味は？", choices: ["家", "学校", "病院", "公園"], a: 1 },
  { q: "\"library\" の意味は？", choices: ["図書館", "病院", "学校", "公園"], a: 0 },
  { q: "\"Monday\" の意味は？", choices: ["日曜日", "月曜日", "火曜日", "水曜日"], a: 1 },
  { q: "\"January\" の意味は？", choices: ["1月", "2月", "12月", "6月"], a: 0 },
  { q: "\"What time is it?\" の意味は？", choices: ["元気ですか", "何時ですか", "どこですか", "誰ですか"], a: 1 },
  { q: "\"How are you?\" の意味は？", choices: ["あなたは誰？", "元気ですか？", "どこにいる？", "何歳ですか？"], a: 1 },
  { q: "\"Nice to meet you.\" の意味は？", choices: ["さようなら", "はじめまして", "ありがとう", "ごめんなさい"], a: 1 },
  { q: "「私の」を表す語は？", choices: ["I", "me", "my", "mine"], a: 2 },
  { q: "「彼の」を表す語は？", choices: ["he", "him", "his", "he's"], a: 2 },
  { q: "「彼女の」を表す語は？", choices: ["she", "her", "hers", "she's"], a: 1 },
  { q: "\"can\" の意味として正しいのは？", choices: ["〜すべき", "〜できる", "〜したい", "〜している"], a: 1 },
  { q: "\"like\" の意味は？", choices: ["嫌う", "好む", "食べる", "行く"], a: 1 },
  { q: "\"play\" の意味は？", choices: ["勉強する", "遊ぶ・する", "眠る", "書く"], a: 1 },
  { q: "「1」を英語で書くと？", choices: ["one", "two", "three", "four"], a: 0 },
  { q: "「5」を英語で書くと？", choices: ["three", "four", "five", "six"], a: 2 },
];
const ENGLISH_L2 = [
  { q: "「彼女は毎日勉強します」を選べ", choices: ["She study every day.", "She studies every day.", "She studying every day.", "She studyed every day."], a: 1 },
  { q: "「彼は野球をします」を選べ", choices: ["He play baseball.", "He plays baseball.", "He playing baseball.", "He played baseball（現在の話として）"], a: 1 },
  { q: "3人称単数の動詞変化：\"go\" →", choices: ["goes", "gos", "going", "goed"], a: 0 },
  { q: "3人称単数の動詞変化：\"watch\" →", choices: ["watchs", "watches", "watching", "watchies"], a: 1 },
  { q: "疑問文の作り方は？ \"You like cats.\" →", choices: ["You like cats?", "Do you like cats?", "Are you like cats?", "Like you cats?"], a: 1 },
  { q: "疑問文の作り方は？ \"She plays tennis.\" →", choices: ["Does she play tennis?", "Do she plays tennis?", "Is she play tennis?", "She plays tennis?"], a: 0 },
  { q: "「〜しないでください」を表すのは？", choices: ["Please not.", "Don't ~", "Not ~", "No ~ please"], a: 1 },
  { q: "「私は行きません」を選べ", choices: ["I don't go.", "I not go.", "I doesn't go.", "I isn't go."], a: 0 },
  { q: "「彼は行きません」を選べ", choices: ["He don't go.", "He doesn't go.", "He isn't go.", "He not goes."], a: 1 },
  { q: "\"There ___ two cats.\" に入る語は？", choices: ["is", "are", "am", "be"], a: 1 },
  { q: "\"There ___ a book on the desk.\" に入る語は？", choices: ["is", "are", "am", "be"], a: 0 },
  { q: "現在進行形「〜している」の作り方は？", choices: ["be動詞 + 動詞ing", "動詞 + ed", "動詞のみ", "will + 動詞"], a: 0 },
  { q: "「私は今、勉強しています」を選べ", choices: ["I study now.", "I am studying now.", "I studies now.", "I studied now."], a: 1 },
  { q: "過去形「〜した」で正しいのは？", choices: ["I play tennis yesterday.", "I played tennis yesterday.", "I plays tennis yesterday.", "I playing tennis yesterday."], a: 1 },
  { q: "\"go\" の過去形は？", choices: ["goed", "went", "gone", "going"], a: 1 },
  { q: "\"see\" の過去形は？", choices: ["seed", "saw", "seen", "sees"], a: 1 },
  { q: "\"have\" の過去形は？", choices: ["haved", "has", "had", "having"], a: 2 },
  { q: "未来「〜するつもりです」の表現は？", choices: ["I will go.", "I am go.", "I goes.", "I to go."], a: 0 },
  { q: "「〜より…だ」比較級の作り方（taller）は何形？", choices: ["原級", "比較級", "最上級", "進行形"], a: 1 },
  { q: "「一番〜だ」最上級の作り方（tallest）は何形？", choices: ["原級", "比較級", "最上級", "進行形"], a: 2 },
  { q: "\"good\" の比較級は？", choices: ["gooder", "better", "best", "more good"], a: 1 },
  { q: "\"many\" の比較級は？", choices: ["manyer", "more", "most", "much"], a: 1 },
  { q: "「〜することが好き」の表現は？", choices: ["like to do / like doing", "like do", "like did", "like does"], a: 0 },
  { q: "助動詞 \"must\" の意味は？", choices: ["〜かもしれない", "〜しなければならない", "〜できる", "〜だろう"], a: 1 },
  { q: "\"have to\" の意味に近いのは？", choices: ["〜してもよい", "〜する必要がある", "〜すべきでない", "〜したい"], a: 1 },
  { q: "「なぜ〜？」を表す疑問詞は？", choices: ["What", "When", "Where", "Why"], a: 3 },
  { q: "「どのように〜？」を表す疑問詞は？", choices: ["Who", "How", "Which", "Whose"], a: 1 },
  { q: "\"because\" の意味は？", choices: ["しかし", "なぜなら", "そして", "もし"], a: 1 },
  { q: "命令文「立ちなさい」を選べ", choices: ["You stand up.", "Stand up.", "Standing up.", "To stand up."], a: 1 },
  { q: "「〜してはいけません」を選べ", choices: ["Don't run.", "Not run.", "No running here only.", "Never do run."], a: 0 },
];
const ENGLISH_L3 = [
  { q: "\"I want ___ book.\" に入る冠詞は？", choices: ["a", "an", "the（初出のとき）", "無冠詞"], a: 0 },
  { q: "\"She has ___ umbrella.\" に入る冠詞は？", choices: ["a", "an", "the", "無冠詞"], a: 1 },
  { q: "\"to不定詞\"の基本の形は？", choices: ["to + 動詞の原形", "to + ing形", "to + 過去形", "to + 名詞のみ"], a: 0 },
  { q: "「私は英語を勉強するために日本に来た」の下線部の働きは？（came to study）", choices: ["名詞的用法", "形容詞的用法", "副詞的用法（目的）", "受け身"], a: 2 },
  { q: "動名詞（〜すること）の作り方は？", choices: ["動詞 + ing", "to + 動詞", "動詞 + ed", "動詞の原形のみ"], a: 0 },
  { q: "\"I enjoy ___ music.\" に入る形は？", choices: ["listen", "to listen", "listening", "listened"], a: 2 },
  { q: "\"It is important ___ study hard.\" に入る語は？", choices: ["to", "for", "of", "that"], a: 0 },
  { q: "受け身「〜される」の基本形は？", choices: ["be動詞 + 過去分詞", "be動詞 + ing", "have + 過去分詞", "will + 動詞"], a: 0 },
  { q: "\"This book is written ___ him.\" に入る語は？", choices: ["with", "by", "for", "to"], a: 1 },
  { q: "現在完了「ずっと〜している」の形は？", choices: ["have/has + 過去分詞", "have/has + ing", "be + 過去分詞", "will + have"], a: 0 },
  { q: "\"I have ___ finished my homework.\" に入る語は？", choices: ["already", "yet（肯定文の途中）", "ever（肯定文で使用）", "since"], a: 0 },
  { q: "関係代名詞 \"who\" が説明するのは？", choices: ["物", "人", "場所", "時間"], a: 1 },
  { q: "関係代名詞 \"which\" が説明するのは？", choices: ["人のみ", "物や動物", "場所のみ", "時間のみ"], a: 1 },
  { q: "\"The boy ___ is running is Tom.\" に入る関係代名詞は？", choices: ["who", "which", "whose", "whom"], a: 0 },
  { q: "接続詞 \"if\" の意味は？", choices: ["しかし", "もし〜ならば", "なぜなら", "〜だけれど"], a: 1 },
  { q: "接続詞 \"though\" の意味は？", choices: ["〜だけれど", "もし", "なぜなら", "そして"], a: 0 },
  { q: "「〜する時」を表す接続詞は？", choices: ["when", "why", "how", "what"], a: 0 },
  { q: "比較の \"as ... as\" の意味は？", choices: ["〜より…", "〜と同じくらい…", "一番…", "〜ほど…でない（否定なし）"], a: 1 },
  { q: "\"not as ... as\" の意味は？", choices: ["〜と同じくらい", "〜ほど…でない", "一番…", "〜より…"], a: 1 },
  { q: "感嘆文 \"How beautiful!\" の意味に近いのは？", choices: ["なんて美しいの！", "美しいですか？", "美しくない", "美しくしてください"], a: 0 },
  { q: "\"Could you ___ me?\" （丁寧な依頼）に入る語は？", choices: ["help", "helps", "helping", "helped"], a: 0 },
  { q: "\"May I ___ your pen?\" に入る語は？", choices: ["use", "uses", "using", "used"], a: 0 },
  { q: "\"I think that he is right.\" のthatの働きは？", choices: ["関係代名詞", "接続詞（〜ということ）", "指示代名詞", "疑問詞"], a: 1 },
  { q: "\"give A B\"（AにBを与える）の形をとる動詞はどれ？", choices: ["give", "look", "go", "run"], a: 0 },
  { q: "\"call A B\"（AをBと呼ぶ）の形をとる文はどれ？", choices: ["We call him Tom.", "We call to him.", "We call him for Tom.", "We call at him."], a: 0 },
  { q: "\"There is a pen ___ the desk.\" に入る前置詞は？", choices: ["on", "at", "to", "by"], a: 0 },
  { q: "\"I was born ___ 2010.\" に入る前置詞は？", choices: ["at", "on", "in", "for"], a: 2 },
  { q: "\"look forward to ___\" の後に来る形は？", choices: ["動詞の原形", "ing形", "過去形", "to不定詞"], a: 1 },
  { q: "\"It is ... for 人 to do\" の構文の意味は？", choices: ["(人)にとって…するのは〜だ", "(人)は…しなければならない", "(人)は…できない", "(人)は…したくない"], a: 0 },
  { q: "\"as soon as\" の意味は？", choices: ["〜するとすぐに", "〜する前に", "〜した後で", "〜する間に"], a: 0 },
];
